# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'
    branches:
      - 'master'
      - 'dev'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: Rust cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          # An additional key for the cache
          key: test
          # An additional cache key that is stable over multiple jobs
          sharedKey: test
          # The working directory this action should operate in
          working-directory: src-tauri/
          # The target dir that should be cleaned and persisted, defaults to `./target`
          target-dir: ./target
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.17.1
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build App
        run: pnpm run build
      - name: Upload artifacts linux
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: SnapCompanion-linux
          if-no-files-found: error
          path: |
              src-tauri/target/release/bundle/deb/*.deb
              src-tauri/target/release/bundle/appimage/*.AppImage
      - name: Upload artifacts windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: SnapCompanion-windows
          if-no-files-found: error
          path: src-tauri\target\release\SnapCompanion.exe
      - name: Upload artifacts macos
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: SnapCompanion-macos
          if-no-files-found: error
          path: src-tauri/target/release/bundle/macos/


